services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spa-client-app
    restart: unless-stopped
    working_dir: /var/www/
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www
    networks:
      - spa-client-network
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: spa-client-nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - spa-client-network
    depends_on:
      - app
      - node
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:14-alpine
    container_name: spa-client-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata-client:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - spa-client-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  node:
    image: node:lts
    container_name: spa-client-node
    working_dir: /var/www
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www
    ports:
      - "5174:5173"
    networks:
      - spa-client-network
    command: bash -c "npm install && npm run dev"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

networks:
  spa-client-network:
    name: book-sell-spa-client-network
    driver: bridge

volumes:
  pgdata-client:
