services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spa-client-app
    restart: unless-stopped
    working_dir: /var/www/
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www
    networks:
      - spa-client-network
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: spa-client-nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - spa-client-network
    depends_on:
      - app
      - node
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:14-alpine
    container_name: spa-client-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata-client:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - spa-client-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  node:
    image: node:lts
    container_name: spa-client-node
    working_dir: /var/www
    user: "0:0"
    volumes:
      - ./:/var/www
    ports:
      - "5174:5173"
      - "5175:5174"
      - "5176:5175"
      - "24678:24678" # Порт для HMR Vite
    networks:
      - spa-client-network
      - book-sell-system_app-network  # Исправляем название сети серверного приложения
    environment:
      - VITE_PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - VITE_PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
      - VITE_PUSHER_HOST=${PUSHER_HOST}
      - VITE_PUSHER_PORT=${PUSHER_PORT}
      - VITE_PUSHER_SCHEME=${PUSHER_SCHEME}
      - BROADCAST_DRIVER=${BROADCAST_DRIVER}
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
      - HOST=0.0.0.0
      - NODE_ENV=development
      - NPM_CONFIG_CACHE=/tmp/.npm
    command: >
      bash -c "
        echo 'Исправляем права на node_modules...' &&
        mkdir -p /var/www/node_modules &&
        chmod -R 777 /var/www/node_modules &&
        echo 'Устанавливаю зависимости...' &&
        npm install &&
        echo 'Устанавливаю дополнительные зависимости для Pusher...' &&
        npm install --save-dev laravel-echo pusher-js &&
        echo 'Запускаю Vite для разработки...' &&
        npm run dev -- --host 0.0.0.0 --port 5173
      "
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

networks:
  spa-client-network:
    name: book-sell-spa-client-network
    driver: bridge
  book-sell-system_app-network:
    name: book-sell-system_app-network
    external: true  # Указываем, что сеть уже существует

volumes:
  pgdata-client:
